volumes:
  data:

version: '3.3'
services:
  postgredb:
    container_name: postgredb
    hostname: postgredb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=merenda
      - POSTGRES_DB=gomoku
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  gomoku-service-1:
    container_name: gomoku-service-1
    hostname: gomoku-service-1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://localhost:5432/gomoku?user=postgres&password=merenda"
      port: 8081
    ports:
      - 8081:8081

  gomoku-service-2:
    container_name: gomoku-service-2
    hostname: gomoku-service-2
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      port: 8082
      JDBC_DATABASE_URL: "jdbc:postgresql://localhost:5432/gomoku?user=postgres&password=merenda"
    ports:
      - 8082:8082

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./:/etc/nginx
      - ./static-content:/static
    depends_on:
      - gomoku-service-1
      - gomoku-service-2