CREATE TABLE IF NOT EXISTS boards (
    boardId INTEGER UNIQUE PRIMARY KEY,
    pieces VARCHAR(2048) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    userId  SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    token VARCHAR(36) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS lobby (
    lobbyId  SERIAL PRIMARY KEY,
    p1 INTEGER NOT NULL REFERENCES users(userId) ON DELETE CASCADE,
    p2 INTEGER REFERENCES users(userId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS games (
    gameId  VARCHAR(36) UNIQUE PRIMARY KEY,
    board INTEGER NOT NULL REFERENCES boards(boardId) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    state VARCHAR(8) NOT NULL CHECK (state IN ('ACTIVE', 'FINISHED'))
);

CREATE TABLE IF NOT EXISTS game_users (
    game VARCHAR(36) NOT NULL REFERENCES games(gameId) ON DELETE CASCADE,
    player_white INTEGER NOT NULL REFERENCES users(userId) ON DELETE CASCADE,
    player_black INTEGER NOT NULL REFERENCES users(userId) ON DELETE CASCADE,
    PRIMARY KEY (game, player_white, player_black)
);